nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    expose_headers:
      - Link
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["X-Custom-Auth", "Content-Type", "Link", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      expose_headers:
        - Link
      max_age: 3600
    "^/":
      origin_regex: true
      allow_origin: ["^https://localhost:[0-9]+"]
      allow_headers: ["X-Custom-Auth", "Content-Type", "Link", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      expose_headers:
        - Link
      max_age: 3600
      hosts: ['^api\.']
